USE [master]
GO
/****** Object:  Database [LuminaTechDB]    Script Date: 12/04/2026 12:40:50 ******/
CREATE DATABASE [LuminaTechDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LuminaTechDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER01\MSSQL\DATA\LuminaTechDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LuminaTechDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER01\MSSQL\DATA\LuminaTechDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [LuminaTechDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LuminaTechDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LuminaTechDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [LuminaTechDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LuminaTechDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LuminaTechDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LuminaTechDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LuminaTechDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LuminaTechDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LuminaTechDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LuminaTechDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LuminaTechDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LuminaTechDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LuminaTechDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LuminaTechDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LuminaTechDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LuminaTechDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LuminaTechDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LuminaTechDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LuminaTechDB] SET RECOVERY FULL 
GO
ALTER DATABASE [LuminaTechDB] SET  MULTI_USER 
GO
ALTER DATABASE [LuminaTechDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LuminaTechDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LuminaTechDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LuminaTechDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LuminaTechDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LuminaTechDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [LuminaTechDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LuminaTechDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [LuminaTechDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [LuminaTechDB]
GO
/****** Object:  Table [dbo].[Aulas]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aulas](
	[ID_Aula] [int] IDENTITY(1,1) NOT NULL,
	[ID_Curso] [int] NOT NULL,
	[Titulo_Aula] [varchar](150) NOT NULL,
	[Conteudo_Texto] [text] NULL,
	[Ordem] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Aula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Avaliacoes]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Avaliacoes](
	[ID_Avaliacao] [int] IDENTITY(1,1) NOT NULL,
	[ID_Aula] [int] NOT NULL,
	[Pergunta] [text] NOT NULL,
	[Opcao_A] [varchar](255) NOT NULL,
	[Opcao_B] [varchar](255) NOT NULL,
	[Opcao_C] [varchar](255) NOT NULL,
	[Opcao_D] [varchar](255) NOT NULL,
	[Resposta_Correta] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Avaliacao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cursos]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cursos](
	[ID_Curso] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Curso] [varchar](100) NOT NULL,
	[Descricao] [text] NULL,
	[Nivel] [varchar](20) NULL,
	[Carga_Horaria] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Curso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medalhas]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medalhas](
	[ID_Medalha] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Medalha] [varchar](50) NOT NULL,
	[Descricao] [varchar](255) NULL,
	[Icone_Caminho] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Medalha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Progresso]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Progresso](
	[ID_Progresso] [int] IDENTITY(1,1) NOT NULL,
	[ID_Usuario] [int] NOT NULL,
	[ID_Aula] [int] NOT NULL,
	[Nota_Obtida] [decimal](5, 2) NULL,
	[Data_Tentativa] [datetime] NULL,
	[Status_Aula] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Progresso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario_Medalhas]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario_Medalhas](
	[ID_Conquista] [int] IDENTITY(1,1) NOT NULL,
	[ID_Usuario] [int] NOT NULL,
	[ID_Medalha] [int] NOT NULL,
	[Data_Ganho] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Conquista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 12/04/2026 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[ID_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Completo] [varchar](100) NOT NULL,
	[CPF] [char](11) NOT NULL,
	[Data_Nascimento] [date] NOT NULL,
	[Telefone] [varchar](15) NULL,
	[Email] [varchar](100) NOT NULL,
	[Senha_Acesso] [varchar](255) NOT NULL,
	[Perfil_Usuario] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Progresso] ADD  DEFAULT (getdate()) FOR [Data_Tentativa]
GO
ALTER TABLE [dbo].[Usuario_Medalhas] ADD  DEFAULT (getdate()) FOR [Data_Ganho]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ('Aluno') FOR [Perfil_Usuario]
GO
ALTER TABLE [dbo].[Aulas]  WITH CHECK ADD  CONSTRAINT [FK_Curso_Aula] FOREIGN KEY([ID_Curso])
REFERENCES [dbo].[Cursos] ([ID_Curso])
GO
ALTER TABLE [dbo].[Aulas] CHECK CONSTRAINT [FK_Curso_Aula]
GO
ALTER TABLE [dbo].[Avaliacoes]  WITH CHECK ADD  CONSTRAINT [FK_Aula_Avaliacao] FOREIGN KEY([ID_Aula])
REFERENCES [dbo].[Aulas] ([ID_Aula])
GO
ALTER TABLE [dbo].[Avaliacoes] CHECK CONSTRAINT [FK_Aula_Avaliacao]
GO
ALTER TABLE [dbo].[Progresso]  WITH CHECK ADD  CONSTRAINT [FK_Aula_Progresso] FOREIGN KEY([ID_Aula])
REFERENCES [dbo].[Aulas] ([ID_Aula])
GO
ALTER TABLE [dbo].[Progresso] CHECK CONSTRAINT [FK_Aula_Progresso]
GO
ALTER TABLE [dbo].[Progresso]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Progresso] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuarios] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Progresso] CHECK CONSTRAINT [FK_Usuario_Progresso]
GO
ALTER TABLE [dbo].[Usuario_Medalhas]  WITH CHECK ADD  CONSTRAINT [FK_Tipo_Medalha] FOREIGN KEY([ID_Medalha])
REFERENCES [dbo].[Medalhas] ([ID_Medalha])
GO
ALTER TABLE [dbo].[Usuario_Medalhas] CHECK CONSTRAINT [FK_Tipo_Medalha]
GO
ALTER TABLE [dbo].[Usuario_Medalhas]  WITH CHECK ADD  CONSTRAINT [FK_User_Medalha] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuarios] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Usuario_Medalhas] CHECK CONSTRAINT [FK_User_Medalha]
GO
ALTER TABLE [dbo].[Cursos]  WITH CHECK ADD CHECK  (([Nivel]='Avançado' OR [Nivel]='Intermediário' OR [Nivel]='Básico'))
GO
ALTER TABLE [dbo].[Progresso]  WITH CHECK ADD CHECK  (([Status_Aula]='Concluído' OR [Status_Aula]='Revisar' OR [Status_Aula]='Em Aberto'))
GO
USE [master]
GO
ALTER DATABASE [LuminaTechDB] SET  READ_WRITE 
GO
